line_follower_node:
  ros__parameters:
    image_topic: /camera/image_raw
    cmd_vel_topic: /cmd_vel
    debug_image_topic: /line_follower/debug_image
    mask_topic: /line_follower/mask

    detection_mode: brightness

    brightness_threshold: 180
    blur_kernel: 5
    morph_kernel: 5

    h_min: 18
    s_min: 70
    v_min: 70
    h_max: 45
    s_max: 255
    v_max: 255

    roi_1: [95.0, 140.0, 95.0, 225.0, 0.15]
    roi_2: [132.0, 185.0, 80.0, 240.0, 0.30]
    roi_3: [178.0, 236.0, 60.0, 260.0, 0.55]

    base_speed: 0.13

    kp_angular: 1.40
    ki_angular: 0.00
    kd_angular: 0.00

    min_linear_speed: 0.13
    max_linear_speed: 0.13

    min_angular_speed: 0.00
    max_angular_speed: 0.80

    angular_sign: 1.0
    slowdown_on_error: 0.00
    deadband_error: 0.04
    integral_limit: 0.00

    min_contour_area: 40.0
    search_when_lost: false
    search_angular_speed: 0.40

line_follower_pose_node:
  ros__parameters:
    enable_pose_init: true
    move_time_ms: 1000
    use_deviation: true

    servo_1: 1500
    servo_3: 500
    servo_4: 2265
    servo_5: 1080
    servo_6: 1500
